### PR TITLE
fix iteration count mismatch in JailBreaker.run()

### PR DESCRIPTION
**Pull request by ddooom**
fix iteration count mismatch in JailBreaker.run()

### CODE REVIEW

**Comment by ddooom** [comment]
Is it your intention to append `JailBreakResult` to the `result` and not add 1 to `cnt` even if an exception occurs?

https://github.com/hskimim/prompt-hacker/blob/0f2c4edf5d9a2480f58da0458d375c4e3d96e54c/prompt_hacker/attack/jailbreak.py#L67

**Comment by hskimim** [comment]
I acknowledged. But `if cnt == inputs.sample_size:` seems to be more clear.

**Comment by hskimim** [comment]
> append

When the user will filter err = False and check the data, I wanted the number of data to be as large as sample_size. 
This seems to be a matter of choice.

**Comment by ddooom** [comment]
> > append
> 
> When the user will filter err = False and check the data, I wanted the number of data to be as large as sample_size. This seems to be a matter of choice.

**Pull request merged**
